### ISSUE TITLE
关闭标签页

### ISSUE THREAD

**Issue by yihr** [letsbug/vava#1]
打开多个标签页，点击任意 tab 上的 X ，关闭的不是对应tab，而是打开页面的tab页

**Comment by letsbug** [comment]
请问是什么环境下出现的问题呢？操作系统、浏览器、以及版本。

**Comment by letsbug** [comment]
> 打开多个标签页，点击任意 tab 上的 X ，关闭的不是对应tab，而是打开页面的tab页

请问是什么环境下出现的问题呢？操作系统、浏览器、以及版本。

**Comment by letsbug** [comment]
> 打开多个标签页，点击任意 tab 上的 X ，关闭的不是对应tab，而是打开页面的tab页

已修复！！！感谢反馈！
